### ISSUE TITLE
Shipping api_value method isinstance checking wrong

### ISSUE THREAD

**Issue by NameX44** [Mangopay/mangopay2-python-sdk#271]
Hi,

ShippingField api_value method seems to be wrong : 

`
    def api_value(self, value):
        value = super(ShippingField, self).api_value(value)

        if isinstance(value, Billing):
            value = {
                'Address': value.address
            }

        return value
`

the isinstance is looking for Billing instead of a Shipping.

Thanks,

**Comment by samitnuk** [comment]
@mangomaxoasis @catacraciun

As I can see, this will be fixed in https://github.com/Mangopay/mangopay2-python-sdk/pull/270. Could you please inform us when we can expect a new release of this SDK?

Currently, with this bug, it is not possible to [Cancel or Validate a PreAuthorization](https://docs.mangopay.com/endpoints/v2.01/preauthorizations#e186_cancel-a-preauthorization).

Version 3.8.5 on this:
```python
preauthorization.payment_status = PAYMENT_STATUS_CHOICES.canceled
preauthorization.save()
```
Produces:
```bash
AttributeError: 'Shipping' object has no attribute 'to_api_json'
```

**Comment by samitnuk** [comment]
@mangomaxoasis @catacraciun

I have created PR #272 to recreate with the tests the issue described here. The current tests do not catch this issue because in the mocked data for pre-authorizations there is no "Shipping". But MangoPay API returns "Shipping" in the "real" response. For example a part of the response body for the "real" pre-authorization data (from the sandbox):
![img 2021-02-18 в 22 33 02](https://user-images.githubusercontent.com/16734295/108418780-5d110c00-723a-11eb-892e-96b3fc0211ca.png)

**Comment by dduwoyemgp** [comment]
Hello @NameX44 and @samitnuk 
Have you checked the last release of the Python SDK that would resolved your issue. Don't hesitate to close this issue accordingly

**Comment by samitnuk** [comment]
Hi @dduwoyemgp  

Thank you for the information about the last release (`3.9.0`). Will check it as soon as will be able.

**Comment by dduwoyemgp** [comment]
> Hi @dduwoyemgp
> 
> Thank you for the information about the last release (`3.9.0`). Will check it as soon as will be able.

Hello @samitnuk 
The `3.9.0` version has already been released: https://pypi.org/project/mangopaysdk/
